# Generated by Django 5.0 on 2023-12-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='title',
            field=models.TextField(default='Code Query', max_length=5000),
        ),
    ]
